server:
  port: 8100
spring:
  application:
    name: currency-conversion-service
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411/
  rabbitmq:
    host: rabbitmq-master
    port: 5672
  cloud:
    bus:
      enabled: true
      destination: configXchangebus
#currency-exchange-service:
#  ribbon:
#    listOfServers: http://localhost:8000, http://localhost:8001
eureka:
  client:
    service-url:
      default-zone: ${currency-conversion-service.eureka.url:http://currency-registry-service:8761/eureka}
        
      
      