server:
  port: 8100
spring:
  application:
    name: currency-conversion-service
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.103:9411/
  rabbitmq:
    host: 192.168.99.103
    port: 5672
  cloud:
    bus:
      enabled: true
      destination: configXchangebus
#currency-exchange-service:
#  ribbon:
#    listOfServers: http://localhost:8000, http://localhost:8001
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
        
      
      