spring:
  cloud:
    bus:
      enabled: true
      destination: configXchangebus
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productDb;DB_CLOSE_DELAY=-1
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411/
  rabbitmq:
    host: rabbitmq-master
    port: 5672


server:
  port: 8000
eureka:
  client:
    service-url:
      default-zone: ${currency-exchange-service.eureka.url:http://currency-registry-service:8761/eureka}
 

