spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IbrahimHanif/MicroServiceReskill.git
          searchPaths: CurrencyConversionProject/configdata
          skipSslValidation: true
  application:
    name: currency-config
server:
  port: 8888
